/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EmployeeAction;
import dto.Employee;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quay
 */
public class MainFrm extends javax.swing.JFrame {
    
    EmployeeAction ac = null;

    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
        ac = new EmployeeAction();
        setSize(600, 600);
        setLocationRelativeTo(null);
        loadTable(ac.readAll());
    }
    
    void loadTable(List<Employee> list) {
        Vector colum = new Vector();
        colum.add("code");
        colum.add("name");
        colum.add("age");
        colum.add("salary");
        Vector rows = new Vector();
        for (Employee e : list) {
            Vector row = new Vector();
            row.add(e.getCode());
            row.add(e.getName());
            row.add(e.getAge());
            row.add(e.getSalary());
            rows.add(row);
        }
        tblEmployee.setModel(new DefaultTableModel(rows, colum));
        tblEmployee.updateUI();
        spnEmployee.setViewportView(this.tblEmployee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        spnEmployee = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        lblCode = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EM");
        setMaximumSize(new java.awt.Dimension(20, 10));
        setMinimumSize(new java.awt.Dimension(20, 10));
        setPreferredSize(new java.awt.Dimension(20, 10));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        spnEmployee.setViewportView(tblEmployee);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 478;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(spnEmployee, gridBagConstraints);

        lblCode.setText("Code");
        lblCode.setAlignmentX(1.0F);
        lblCode.setAlignmentY(1.0F);
        lblCode.setMaximumSize(new java.awt.Dimension(20, 10));
        lblCode.setMinimumSize(new java.awt.Dimension(20, 10));
        lblCode.setName(""); // NOI18N
        lblCode.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblCode, gridBagConstraints);

        lblName.setText("Name");
        lblName.setAlignmentX(1.0F);
        lblName.setAlignmentY(1.0F);
        lblName.setMaximumSize(new java.awt.Dimension(20, 10));
        lblName.setMinimumSize(new java.awt.Dimension(20, 10));
        lblName.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblName, gridBagConstraints);

        lblAge.setText("Age");
        lblAge.setAlignmentX(1.0F);
        lblAge.setAlignmentY(1.0F);
        lblAge.setMaximumSize(new java.awt.Dimension(20, 10));
        lblAge.setMinimumSize(new java.awt.Dimension(20, 10));
        lblAge.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblAge, gridBagConstraints);

        lblSalary.setText("Salary");
        lblSalary.setAlignmentX(1.0F);
        lblSalary.setAlignmentY(1.0F);
        lblSalary.setMaximumSize(new java.awt.Dimension(20, 10));
        lblSalary.setMinimumSize(new java.awt.Dimension(20, 10));
        lblSalary.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblSalary, gridBagConstraints);

        txtCode.setAlignmentX(1.0F);
        txtCode.setAlignmentY(1.0F);
        txtCode.setMaximumSize(new java.awt.Dimension(20, 10));
        txtCode.setMinimumSize(new java.awt.Dimension(20, 10));
        txtCode.setPreferredSize(new java.awt.Dimension(20, 10));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtCode, gridBagConstraints);

        txtName.setAlignmentX(1.0F);
        txtName.setAlignmentY(1.0F);
        txtName.setMaximumSize(new java.awt.Dimension(20, 10));
        txtName.setMinimumSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtName, gridBagConstraints);

        txtAge.setAlignmentX(1.0F);
        txtAge.setAlignmentY(1.0F);
        txtAge.setMaximumSize(new java.awt.Dimension(20, 10));
        txtAge.setMinimumSize(new java.awt.Dimension(20, 10));
        txtAge.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtAge, gridBagConstraints);

        txtSalary.setAlignmentX(1.0F);
        txtSalary.setAlignmentY(1.0F);
        txtSalary.setMaximumSize(new java.awt.Dimension(20, 10));
        txtSalary.setMinimumSize(new java.awt.Dimension(20, 10));
        txtSalary.setPreferredSize(new java.awt.Dimension(20, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(txtSalary, gridBagConstraints);

        btnCreate.setText("Create");
        btnCreate.setAlignmentX(1.0F);
        btnCreate.setAlignmentY(1.0F);
        btnCreate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCreate.setMaximumSize(new java.awt.Dimension(65, 23));
        btnCreate.setMinimumSize(new java.awt.Dimension(65, 23));
        btnCreate.setPreferredSize(new java.awt.Dimension(65, 23));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnCreate, gridBagConstraints);

        btnUpdate.setText("Update");
        btnUpdate.setAlignmentX(1.0F);
        btnUpdate.setAlignmentY(1.0F);
        btnUpdate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnUpdate.setMaximumSize(new java.awt.Dimension(65, 23));
        btnUpdate.setMinimumSize(new java.awt.Dimension(65, 23));
        btnUpdate.setPreferredSize(new java.awt.Dimension(65, 23));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnUpdate, gridBagConstraints);

        btnDelete.setText("Delete");
        btnDelete.setAlignmentX(1.0F);
        btnDelete.setAlignmentY(1.0F);
        btnDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnDelete.setMaximumSize(new java.awt.Dimension(65, 23));
        btnDelete.setMinimumSize(new java.awt.Dimension(65, 23));
        btnDelete.setPreferredSize(new java.awt.Dimension(65, 23));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnDelete, gridBagConstraints);

        btnRefresh.setText("Refresh");
        btnRefresh.setAlignmentX(1.0F);
        btnRefresh.setAlignmentY(1.0F);
        btnRefresh.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRefresh.setMaximumSize(new java.awt.Dimension(65, 23));
        btnRefresh.setMinimumSize(new java.awt.Dimension(65, 23));
        btnRefresh.setPreferredSize(new java.awt.Dimension(65, 23));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(btnRefresh, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String code = txtCode.getText().trim();
        double salary = Double.parseDouble(txtSalary.getText().trim());
        Employee e = new Employee(code, salary);
        if (ac.update(e) != null) {
            JOptionPane.showMessageDialog(this, "Success");
        } else {
            JOptionPane.showMessageDialog(this, "Fail");
        }
        loadTable(ac.readAll());
        txtCode.setText("");
        txtSalary.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String code = txtCode.getText().trim();
        String name = txtName.getText().trim();
        int age = Integer.parseInt(txtAge.getText().trim());
        double salary = Double.parseDouble(txtSalary.getText().trim());
        Employee e = new Employee(code, name, age, salary);
        if (ac.create(e) != null) {
            JOptionPane.showMessageDialog(this, "Success");
        } else {
            JOptionPane.showMessageDialog(this, "Fail");
        }
        loadTable(ac.readAll());
        txtCode.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtSalary.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        txtCode.setText(String.valueOf(tblEmployee.getValueAt(row, 0)));
        txtName.setText(String.valueOf(tblEmployee.getValueAt(row, 1)));
        txtAge.setText(String.valueOf(tblEmployee.getValueAt(row, 2)));
        txtSalary.setText(String.valueOf(tblEmployee.getValueAt(row, 3)));
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Choose row");
        } else {
            String code = (String) tblEmployee.getValueAt(row, 0);
            if (ac.delete(code)) {
                JOptionPane.showMessageDialog(this, "Success");
                loadTable(ac.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Fail");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadTable(ac.readAll());
        txtCode.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtSalary.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JScrollPane spnEmployee;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
